import "./globals.css";
import * as React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by leo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
